// GENERATED BY CODE! DO NOT MODIFY!
using UnityEngine;
namespace Watermelon
{
	[System.Serializable]
	public class Sounds
	{
        public AudioClip buttonSound;
        public AudioClip finishAudioClip;
        public AudioClip obstacleHitAudioClip;
        public AudioClip drivingAwayAudioClip;
        public AudioClip finalCoinCollectClip;
        public AudioClip bounceSpawnAudioClip;
        public AudioClip bounceHideAudioClip;
        public AudioClip hornShort;
    }
}